package app.amphora.ui

import android.content.Context
import java.io.File
import java.util.Base64

/**
 * Small freestanding x86-64 PE used by the launcher smoke-test button.
 *
 * The program stays alive until Amphora stops the Wine session. Keeping this
 * deterministic fixture inline avoids restoring the old APK-bundled Proton
 * `notepad.exe` and keeps the production APK slim.
 */
object DebugWineFixture {
    private const val FILE_NAME = "wine-smoke-test.exe"

    private val bytes: ByteArray by lazy {
        Base64.getDecoder().decode(EXE_BASE64)
    }

    fun stage(context: Context): File {
        val target = File(context.filesDir, "exe/$FILE_NAME")
        val parent = requireNotNull(target.parentFile)
        check(parent.isDirectory || parent.mkdirs()) {
            "Unable to create debug executable directory"
        }
        if (!target.isFile || !target.readBytes().contentEquals(bytes)) {
            val staging = File(target.absolutePath + ".tmp")
            staging.writeBytes(bytes)
            if (!staging.renameTo(target)) {
                target.writeBytes(bytes)
                staging.delete()
            }
        }
        return target
    }

    // Built from:
    // void mainCRTStartup(void) { for (;;) { __asm__ volatile("pause"); } }
    // clang --target=x86_64-pc-windows-msvc -c -nostdlib fixture.c
    // ld -mi386pep --entry mainCRTStartup --subsystem console fixture.obj
    // strip --strip-all wine-smoke-test.exe
    private const val EXE_BASE64 =
        "TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJAAAAAAAAABQRQAAZIYCAEFyZWoAAAAAAAAAAPAALwILAgIqAAIAAAACAAAAAAAAABAAAAAQAAAAAABAAQAAAAAQAAAAAgAABAAAAAAAAAAFAAIAAAAAAAAwAAAAAgAAWpAAAAMAAAEAACAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAIAAAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAudGV4dAAAADAAAAAAEAAAAAIAAAACAAAAAAAAAAAAAAAAAAAgAABgLmlkYXRhAAAYAAAAACAAAABAAAAAAAAAAAAAAAAAAAQAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADpAAAAAPOQ6fn///8PH0AA//////////8AAAAAAAAAAP//////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
}
